version: '3'
services:
  filebeat:
    command: filebeat -e -strict.perms=false
    environment:
    - ELASTIC_PASSWORD 
    image: docker.elastic.co/beats/filebeat-oss:7.10.2
    restart: unless-stopped
    user: root
    volumes:
    - ./filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
    - /var/lib/docker/containers:/var/lib/docker/containers:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
  journalbeat:
    command: journalbeat -e -strict.perms=false
    environment:
    - ELASTIC_PASSWORD
    - SYSLOG_IDENTIFIER
    image: docker.elastic.co/beats/journalbeat-oss:7.10.2
    restart: unless-stopped
    user: root
    volumes:
    - ./journalbeat.docker.yml:/usr/share/journalbeat/journalbeat.yml:ro
    - /run/log/journal:/run/log/journal:ro
    - /etc/machine-id:/etc/machine-id:ro

