output.elasticsearch:
  hosts: logs.dide.ic.ac.uk:9200
  username: elastic
  password: ${ELASTIC_PASSWORD}
filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
processors:
  - if:
      equals:
        container.name: "hint_hint"
    then:
    - decode_json_fields:
        fields: ["message"]
        process_array: false
        max_depth: 1
        target: "naomi"
        overwrite_keys: false
        add_error_key: true
        
