output.elasticsearch:
  hosts: logs.dide.ic.ac.uk:9200
  username: elastic
  password: ${ELASTIC_PASSWORD}
journalbeat.inputs:
  - paths: [ ]
    seek: tail
    include_matches:
      - syslog.identifier=${SYSLOG_IDENTIFIER}
processors:
  - add_fields:
      fields:
        hostname: ${MACHINE_HOST}
