#!/usr/bin/env bash
set -e

if which -a filebeat > /dev/null; then
    echo "filebeat is already installed"
    exit 0
fi

if ! which -a docker > /dev/null; then
    echo "Please install docker first"
    exit 1
fi

if [ -z $SUDO_USER ]; then
    echo "Run this command with sudo"
    exit 1
fi

wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | \
    apt-key add -
apt-get install -y apt-transport-https
echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | \
    tee -a /etc/apt/sources.list.d/elastic-7.x.list
apt-get update && \
    sudo apt-get install -y filebeat
