#!/usr/bin/env bash
set -e

if [ -z $SUDO_USER ]; then
    echo "Run this command with sudo"
    exit 1
fi

export VAULT_ADDR=https://vault.dide.ic.ac.uk:8200
export VAULT_TOKEN=$(vault login -method=github -token-only)

filebeat keystore create
vault read -field=password secret/logs/users/elastic |
  filebeat keystore add ES_PW --stdin --force
